### PR TITLE
Fix incorrect constructor for Icon and HtmlImport

### PR DESCRIPTION
**Pull request by ZheSun88**
modify the java docs for IronIcon

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons-flow/2)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-Kxgo_BJGNy7pr0Sk_Js:bvxtzc1) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
> ```XML
>             <scope>test</scope>
>         </dependency>
> 
> ```

we don't have this elsewhere and I don't think we should add these todos 

---

*[src/main/java/com/vaadin/ui/icon/Icon.java, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgoQhZMYfm9s-HlWsh:-KxgoQhZMYfm9s-HlWsi:b-4bpw6d) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/Icon.java#L37)):*
> ```Java
>      */
>     public Icon(VaadinIcons icon) {
>         ironIcon(ICON_COLLECTION_NAME,
> ```

replace with `super()`

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgmKSOs3hZ2pXzEJMa:-KxgmKSOs3hZ2pXzEJMb:ba6s5lu) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L26)):*
> ```Java
> /**
>  * Server side component for
>  * <a href="https://github.com/PolymerElements/iron-icons">iron-icon</a>
> ```

This links to `iron-icons`, that is a collection of different icons. It should link to `iron-icon`, that is the actual web component for displaying these icons.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgnGIjJMnlQVDpUjZd:-KxgnGIjJMnlQVDpUjZe:bw5ifuy) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L27)):*
> ```Java
>  * Server side component for
>  * <a href="https://github.com/PolymerElements/iron-icons">iron-icon</a>
>  * element. iron-icons is a utility import that includes the definition for the
> ```

This is not `iron-icons`. There's no "utility import". There's no "import for the default icon set". This whole sentence doesn't make any sense and it can be just removed.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgnrHymIz0eiUxboxq:-KxgnrHymIz0eiUxboxr:b-onx5q8) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L32)):*
> ```Java
>  * 
>  * @author Vaadin Ltd
>  * @see iron-icons
> ```

This doesn't link to anywhere. Should be removed.

`@see` is used to link to some existing Java class or method etc. that is related to this. If you read the javadocs of the class, this would become a link to somewhere, but now that link is probably broken, since there's no "iron-icons"

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgoJxAMkZz0bCuqqgt:-KxgoJxAMkZz0bCuqqgu:b-5oypgb) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L48)):*
> ```Java
>      *            the icon name
>      */
>     public void ironIcon(String collection, String icon) {
> ```

Upper-case: `IronIcon`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-Kxh3i4iuw5Aoab-XgtO:b-jqm26d) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

we don't have this elsewhere and I don't think we should add these todos 
</blockquote></details>

pekka commented in this ticket.  https://github.com/vaadin/flow/issues/2614, but it has been closed.. so ... 

---

*[src/main/java/com/vaadin/ui/icon/Icon.java, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgoQhZMYfm9s-HlWsh:-Kxh4grsLOhingNOZOMW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/Icon.java#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

replace with `super()`
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgmKSOs3hZ2pXzEJMa:-Kxh5uj6npDXLjMwmg4f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L26)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This links to `iron-icons`, that is a collection of different icons. It should link to `iron-icon`, that is the actual web component for displaying these icons.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgnGIjJMnlQVDpUjZd:-Kxh5tzSRKYN7U0kWXZb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L27)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This is not `iron-icons`. There's no "utility import". There's no "import for the default icon set". This whole sentence doesn't make any sense and it can be just removed.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgnrHymIz0eiUxboxq:-Kxh6DkEHEfrqBfLFeLM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L32)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This doesn't link to anywhere. Should be removed.

`@see` is used to link to some existing Java class or method etc. that is related to this. If you read the javadocs of the class, this would become a link to somewhere, but now that link is probably broken, since there's no "iron-icons"
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/icon/IronIcon.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxgoJxAMkZz0bCuqqgt:-Kxh6EDpDfGDgCwukIK4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/src/main/java/com/vaadin/ui/icon/IronIcon.java#L48)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Upper-case: `IronIcon`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by pekam** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhEoDik4zxUFYwKEJ-:b-muxszt) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

pekka commented in this ticket.  https://github.com/vaadin/flow/issues/2614, but it has been closed.. so ... 
</blockquote></details>

Ok. But formulate it better:
"TODO: Remove the dependency below after components have been deployed individually, and replace with vaadin-ordered-layout"
and indent the comment correctly instead of starting from the beginning of the line

---

*[src/main/java/com/vaadin/ui/icon/Icon.java, line 42 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxhEgAydXkXRKSqC6xn:-KxhEgAydXkXRKSqC6xo:b-4tpgty) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/5c0db30a35aa34ffc7f9a6ea604f61763c63aca8/src/main/java/com/vaadin/ui/icon/Icon.java#L42)):*
> ```Java
>         super(ICON_COLLECTION_NAME,
>                 icon.name().toLowerCase().replace('_', '-'));
> ```

Don't add an empty line here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by ZheSun88** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhGPGcfZ9JpnseK_9B:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Ok. But formulate it better:
"TODO: Remove the dependency below after components have been deployed individually, and replace with vaadin-ordered-layout"
and indent the comment correctly instead of starting from the beginning of the line
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/icon/Icon.java, line 42 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-KxhEgAydXkXRKSqC6xn:-KxhGPnyYZeNa-oE1rcx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/5c0db30a35aa34ffc7f9a6ea604f61763c63aca8/src/main/java/com/vaadin/ui/icon/Icon.java#L42)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Don't add an empty line here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by pekam** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhHW3w6H3hN5Ljpq1n:buhotbw) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the whole comment, starting from `<!--` should be indented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhHl3Un6EcMUzH1ByA:b-r407s4) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I meant the whole comment, starting from `<!--` should be indented
</blockquote></details>

umm .okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by pekam** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhIAn0m9dZSTXLKixs:b564y8o) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

umm .okay.
</blockquote></details>

now you have indented both the start of the comment comment and the start of the actual text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhIZFpzzPjjxprmeza:bb7lgoe) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

now you have indented both the start of the comment comment and the start of the actual text
</blockquote></details>

now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by pekam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhIiSRA0zcpAbnYP1N:b-gszycm) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

now?
</blockquote></details>

There should still be at least one space before starting the text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-Kxgo_BJGNy7pr0Sk_Jr:-KxhJE-gudHD4xfJqtgl:bbvr609) ([raw file](https://github.com/vaadin/vaadin-icons-flow/blob/aa49f38c427311ce399f8d51062dbc6268041a85/pom.xml#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

There should still be at least one space before starting the text
</blockquote></details>

looks better?  or should i remove the one space from the next line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-flow/2#-:-KxhJNWfYoiqJ8hvIno2:bnfp4nl)*

**Pull request merged**
